const Advantages = () => {
  return (
    <section id="insurances" className="select-none container mx-auto pt-4 pb-10 w-full max-w-5xl">

      <div className="flex flex-nowrap items-center justify-left md:justify-center px-4 md:px-0 py-8">
        <div className="w-auto pl-5">
          <h2 className="my-4 text-left lg:text-center text-3xl md:text-4xl lg:text-5xl text-colorBlue font-bold">
            Advantages of Text to HTML Converter
          </h2>
        </div>
      </div>

      <div className="w-full mb-6">
        <div className="h-1 mx-8 my-0 py-0 bg-gray-400 bg-opacity-25" />
      </div>

      <div className="flex flex-wrap text-gray-500">
        <div className="w-full px-8 text-sm md:text-md lg:text-lg">
          <div className="mx-auto align-middle">

            <p>Text to HTML Converter is a powerful tool that offers several advantages for users who want to convert their text into HTML code.</p>
            <br />
            <h2 className="font-bold">Here are some of the advantages of using this converter:</h2>
            <br />
            <h3 className="font-bold">Ease of use:</h3>
            <p>Text to HTML Converter is designed to be easy to use even for users without advanced programming knowledge. With an intuitive interface, you can convert your text to HTML in just a few clicks.</p>
            <br />
            <h3 className="font-bold">Time saving:</h3>
            <p>By using the Text to HTML Converter, you save precious time that would be spent manually writing the HTML code corresponding to your text. The tool automates the conversion process, generating the HTML code quickly and efficiently.</p>
            <br />
            <h3 className="font-bold">Accuracy and consistency:</h3>
            <p>When converting your text to HTML manually, it is common to make syntax errors or forget to add necessary HTML elements. With the Text to HTML Converter, you ensure that the generated code is correct and consistent, following HTML best practices.</p>
            <br />
            <h3 className="font-bold">Personalization:</h3>
            <p>Text to HTML Converter provides customization options to suit your needs. You can choose to add line breaks using &lt;br&gt; or &lt;br /&gt; tags, apply styles using Tailwind CSS, or even use your own custom CSS. This allows you to create custom HTML code according to your preferences.</p>
            <br />
            <h3 className="font-bold">Simplified maintenance:</h3>
            <p>By converting your text to HTML using the Converter, you separate the structure from the content. This makes future code maintenance easier as you can make changes to the original text and rerun the conversion to get the updated HTML code. This way, you avoid having to manually make modifications to the HTML code.</p>
            <br />
            <h3 className="font-bold">Compatibility:</h3>
            <p>The HTML code generated by the Converter is compatible with all modern browsers and can be easily incorporated into your web projects. You can use the generated HTML code in blogs, websites, landing pages and more.</p>
            <br />
            <p>Using Text to HTML Converter is an efficient and convenient way to get quality HTML code from your text. Take advantage of all the advantages of this tool and simplify your web page creation work.</p>

          </div>
        </div>
      </div>
    </section>
  )
}
export default Advantages